#version 460
#extension GL_EXT_ray_tracing: require

struct Payload
{
    vec3 rdx;
    vec3 rdy;
    vec3 color;
};

layout(set = 0, binding = 0) uniform View {
    mat4x4 viewInv;
    mat4x4 projInv;
    mat4x4 viewProjInv;
};
layout(set = 0, binding = 2) uniform accelerationStructureEXT topLevel;
layout(set = 1, binding = 0, rgba8) uniform writeonly image2D backBuffer;

layout(location = 0) rayPayloadEXT Payload payload;

vec3 calcRayDifferential(vec3 origin, vec2 xy, vec2 dv,mat4x4 viewInv, mat4x4 projInv)
{
    vec2 p = (xy + dv) * 2 - 1;
    // unproject
    vec4 v = projInv * vec4(p, -1, 1);
    v /= v.w;
    vec3 target = (viewInv * v).xyz;
    return normalize(target - origin);
}

void main()
{
    vec2 fragPos = gl_LaunchIDEXT.xy + 0.5;
    vec2 nxy = fragPos / gl_LaunchSizeEXT.xy * 2 - 1;
    vec4 origin = viewInv * vec4(0, 0, 0, 1);
    vec4 dir = viewProjInv * vec4(nxy, 0, 1);

    vec2 xy = fragPos / gl_LaunchSizeEXT.xy;
    float dx = 1.0 / gl_LaunchSizeEXT.x;
    float dy = 1.0 / gl_LaunchSizeEXT.y;
    payload.rdx = calcRayDifferential(origin.xyz, xy, vec2(dx, 0), viewInv, projInv);
    payload.rdy = calcRayDifferential(origin.xyz, xy, vec2(0, dy), viewInv, projInv);
    payload.color = vec3(0.0);

    float tmin = 0.01, tmax = 100;
    traceRayEXT(topLevel,
        gl_RayFlagsOpaqueEXT,
        0xFF, // cullMask
        0, // sbtRecordOffset
        0, // sbtRecordStride
        0, // missIndex
        origin.xyz, tmin,
        normalize(dir.xyz), tmax,
        0); // payload

    imageStore(backBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(payload.color, 1));
}
