#version 460
#extension GL_EXT_ray_tracing: require

struct Payload
{
    vec3 rdx;
    vec3 rdy;
    vec3 color;
};

layout(set = 0, binding = 0) uniform View {
    mat4x4 viewInv;
    mat4x4 projInv;
    mat4x4 viewProjInv;
};
layout(set = 0, binding = 2) uniform accelerationStructureEXT topLevel;
layout(set = 1, binding = 0, rgba8) uniform writeonly image2D backBuffer;

layout(location = 0) rayPayloadEXT Payload payload;

vec3 calcRayDir(vec2 p, vec2 v, mat4x4 viewProjInv)
{
    p = (p + v) / gl_LaunchSizeEXT.xy * 2 - 1;
    return (viewProjInv * vec4(p, 0, 1)).xyz;
}

void main()
{
    vec2 fragPos = gl_LaunchIDEXT.xy + 0.5;
    vec4 origin = viewInv * vec4(0, 0, 0, 1);
    vec3 dir = calcRayDir(fragPos, vec2(0, 0), viewProjInv);

    payload.rdx = calcRayDir(fragPos, vec2(1, 0), viewProjInv);
    payload.rdy = calcRayDir(fragPos, vec2(0, 1), viewProjInv);
    payload.color = vec3(0.0);

    float tmin = 0.01, tmax = 10;
    traceRayEXT(topLevel,
        gl_RayFlagsOpaqueEXT,
        0xFF, // cullMask
        0, // sbtRecordOffset
        0, // sbtRecordStride
        0, // missIndex
        origin.xyz, tmin,
        normalize(dir), tmax,
        0); // payload

    imageStore(backBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(payload.color, 1));
}
